### PR TITLE
Delete board_of_directors.md

### PR DESCRIPTION
**Pull request by ahamelers**
According to https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2074

### CODE REVIEW

**Comment by ahamelers** [comment]
It turns out I don't have write access to this repo!

**Comment by ryscher** [comment]
This file is referenced by the README, so please update that as well.

**Comment by ryscher** [comment]
@ahamelers Sorry about the access issue; you have access now.

**Comment by ahamelers** [comment]
Done, thanks for catching that!

**Pull request merged**
